/*
  This wrapper file exists soley to silence GCC warnings in
  combination with a funky gcc pragma in the transform_yacc.y file.

  We are not interested in those warnings, since they are on
  autogenerated code which we have no control over.
*/

#include "build/transform_yacc.cc"
